[package]
name = "nil"
description = "🦀🚀🔥 A blazingly fast and memory-efficient implementation of `if err != nil` 🔥🚀🦀"
version = "0.0.999999"
license = "BSD-3-Clause"
edition = "2021"
publish = false
